/*
 * generated by Xtext 2.32.0
 */
package org.xtext.project.lsysgen.ui;

import com.google.inject.Injector;
import org.eclipse.xtext.ui.guice.AbstractGuiceAwareExecutableExtensionFactory;
import org.osgi.framework.Bundle;
import org.osgi.framework.FrameworkUtil;
import org.xtext.project.lsysgen.ui.internal.LsysgenActivator;

/**
 * This class was generated. Customizations should only happen in a newly
 * introduced subclass. 
 */
public class LSysGenExecutableExtensionFactory extends AbstractGuiceAwareExecutableExtensionFactory {

	@Override
	protected Bundle getBundle() {
		return FrameworkUtil.getBundle(LsysgenActivator.class);
	}
	
	@Override
	protected Injector getInjector() {
		LsysgenActivator activator = LsysgenActivator.getInstance();
		return activator != null ? activator.getInjector(LsysgenActivator.ORG_XTEXT_PROJECT_LSYSGEN_LSYSGEN) : null;
	}

}
