/*
 * generated by Xtext 2.32.0
 */
package org.xtext.project.lsysgen.ui;

import org.eclipse.ui.plugin.AbstractUIPlugin;

/**
 * Use this class to register components to be used within the Eclipse IDE.
 */
public class LSysGenUiModule extends AbstractLSysGenUiModule {

	public LSysGenUiModule(AbstractUIPlugin plugin) {
		super(plugin);
	}
}
